# Generated by Django 2.2 on 2020-07-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guardian',
        ),
        migrations.AddField(
            model_name='profile',
            name='elderly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elderly', to=settings.AUTH_USER_MODEL),
        ),
    ]
