apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment_web
  labels:
    app: deployment_web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name: web
          image: python:3.6
          ports:
            - containerPort: 8000