version: '3'
services:
  db:
    restart: always
    build: ./postgres/
    ports:
      - "5433:5433"
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000

    volumes:
      - .:/edms
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - db:db

    depends_on:
      - db