version: '3'
services:
  db:
    restart: always
    build: ./postgres/
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432"
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - media_data:/usr/src/media
    env_file:
      - ./docker/envs/.env
    depends_on:
      - db
networks:
  app-network:
    driver: bridge

volumes:
  media_data:

