version: '3'

services:

  python:

      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
      - .:/edms
      container_name: web
      ports:
        - "7878:8000"
      depends_on:
        - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    container_name: postgres