# Generated by Django 2.2 on 2020-03-17 08:05

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('file_status', models.CharField(max_length=100)),
                ('captured_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(max_length=100)),
                ('assessed_on', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.CharField(max_length=100)),
                ('file_barcode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFileType',
            fields=[
                ('file_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_field_specs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFileDetail',
            fields=[
                ('file_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_barcode', models.CharField(max_length=255)),
                ('document_content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document_file_path', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 8, 5, 11, 478005, tzinfo=utc))),
                ('captured_by', models.CharField(max_length=255)),
                ('assessed_by', models.CharField(max_length=255)),
                ('validated_by', models.CharField(max_length=255)),
                ('document_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DocumentFile')),
                ('file_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DocumentFileType')),
            ],
        ),
        migrations.AddField(
            model_name='documentfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DocumentFileType'),
        ),
    ]
