# Generated by Django 2.2 on 2020-04-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.DocumentState'),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='rejection_by_aq_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='rejection_by_receiver_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='rejection_by_scanner_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='rejection_by_transcriber_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='rejection_by_validation_dec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
