# Generated by Django 2.2 on 2020-03-20 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfiledetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 11, 31, 54, 642654, tzinfo=utc)),
        ),
    ]
