# Generated by Django 2.2 on 2020-04-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfile',
            old_name='rejection_by_transcriber_dec',
            new_name='rejecdatetion_by_transcriber_dec',
        ),
    ]
