# Generated by Django 2.2 on 2020-04-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='admin_read_at',
        ),
    ]
