# Generated by Django 2.2 on 2020-04-21 14:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read_at',
            new_name='user_read_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='admin_read_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='state',
            field=models.CharField(choices=[('REGISTRY', 'Registry'), ('AWAITING_RECEIVE', 'Awaiting Receive'), ('AWAITING_DISASSEMBLER', 'Awaiting Disassembler'), ('AWAITING_SCANNING', 'Awaiting Scanning'), ('AWAITING_REASSEMBLER', 'Awaiting Reassembler'), ('AWAITING_TRANSCRIPTION', 'Awaiting Transcription'), ('AWAITING_QA', 'Awaiting QA'), ('AWAITING_VALIDATION', 'Awaiting Validation'), ('FULL_VALIDATED', 'Fully validated'), ('RECEIVE_REJECTED', 'Returned to Registry'), ('DISASSEMBLER_REJECTED', 'Returned to Scanner'), ('SCANNER_REJECTED', 'Rejected to transcriber'), ('TRANSCRIPTION_REJECTED', 'Rejected at Transcription'), ('QA_REJECTED', 'Rejected at QA'), ('VALIDATION_REJECTED', 'Rejected at Validation'), ('ADMIN_REJECTED', 'Rejected by Admin')], default=app.models.StateOptions('Registry'), max_length=255),
        ),
    ]
