# Generated by Django 2.2 on 2020-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
