# Generated by Django 2.2 on 2020-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filer',
            name='file_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.DocumentFile'),
        ),
    ]
