# Generated by Django 2.2 on 2020-05-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documentfile_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='modification_ended_at',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='modification_started_at',
        ),
    ]
