# Generated by Django 2.2 on 2020-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200402_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstate',
            name='rejection_by_aq_dec',
        ),
        migrations.RemoveField(
            model_name='documentstate',
            name='rejection_by_receiver_dec',
        ),
        migrations.RemoveField(
            model_name='documentstate',
            name='rejection_by_scanner_dec',
        ),
        migrations.RemoveField(
            model_name='documentstate',
            name='rejection_by_transcriber_dec',
        ),
        migrations.RemoveField(
            model_name='documentstate',
            name='rejection_by_validation_dec',
        ),
        migrations.AddField(
            model_name='batch',
            name='rejection_by_receiver_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='rejection_by_aq_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='rejection_by_scanner_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='rejection_by_transcriber_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='rejection_by_validation_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfiledetail',
            name='rejection_by_aq_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfiledetail',
            name='rejection_by_scanner_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfiledetail',
            name='rejection_by_transcriber_dec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfiledetail',
            name='rejection_by_validation_dec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
