# Generated by Django 2.2 on 2020-03-23 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200320_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfiledetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 7, 9, 53, 77610, tzinfo=utc)),
        ),
    ]
