# Generated by Django 2.2 on 2020-03-25 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200323_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='documentfiledetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 18, 26, 128720, tzinfo=utc)),
        ),
    ]
