# Generated by Django 2.2 on 2020-04-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0005_auto_20200402_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstate',
            name='group',
        ),
        migrations.AddField(
            model_name='documentstate',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Permission'),
            preserve_default=False,
        ),
    ]
