# Generated by Django 2.2 on 2020-03-26 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200325_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('state_parameter', models.CharField(max_length=255)),
                ('document_validation_status', models.CharField(max_length=255)),
                ('document_quality_control', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='documentfiledetail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 2, 7, 44, 666523, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='documentfiledetail',
            name='state',
            field=models.ForeignKey(db_column='state_code', default=43, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentState'),
            preserve_default=False,
        ),
    ]
