# Generated by Django 2.2 on 2020-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfiledetail',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
